apiVersion: batch/v1
kind: Job
metadata:
  name: stresstest
spec:
  template:
    metadata:
      name: stresstest-job
    spec:
      restartPolicy: Never
      initContainers:
        - name: load-test-data
          image: arahna/otusdemo:release-0.4
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URI
              value: postgresql://otus:otuspwd@otusdemo-postgresql:5432/otusdemo
          command:
            - sh
            - "-c"
            - |
              bin/cli load-users -count 10000
      containers:
        - name: stresstest
          image: arahna/otusdemo-locust:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_HOST
              value: arch.homework
          command:
            - sh
            - "-c"
            - |
              locust -f /home/locust/locustfile.py --headless -u 10000 -r 100 --host=http://nginx-nginx-ingress-controller.monitoring
  backoffLimit: 0