apiVersion: batch/v1
kind: Job
metadata:
  name: otusdemo-dbmigrations
spec:
  template:
    metadata:
      name: otusdemo-dbmigrations
    spec:
      restartPolicy: Never
      containers:
        - name: dbmigrations
          env:
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: otusdemo-secret
                  key: DB_URI
          image: arahna/otusdemo-migrations:release-0.4
          command:
            - sh
            - "-c"
            - |
              migrate -database $DB_URI -source file://migrations up
  backoffLimit: 6