# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: arahna/otusdemo
  pullPolicy: IfNotPresent
  tag: release-0.3

migrationsimage:
  repository: arahna/otusdemo-migrations
  pullPolicy: IfNotPresent
  tag: release-0.3

service:
  type: NodePort
  port: 9000

postgresql:
  enabled: true
  postgresqlUsername: otus
  postgresqlPassword: otuspwd
  postgresqlDatabase: otusdemo
  service:
    port: "5432"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths: [/otusapp($|/)(.*)]