# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

fullnameOverride: otusdemo

image:
  repository: arahna/otusdemo
  pullPolicy: IfNotPresent
  tag: release-0.4

migrationsimage:
  repository: arahna/otusdemo-migrations
  pullPolicy: IfNotPresent
  tag: release-0.4

service:
  type: NodePort
  port: 9000

postgresql:
  enabled: true
  postgresqlUsername: otus
  postgresqlPassword: otuspwd
  postgresqlDatabase: otusdemo
  service:
    port: "5432"
  metrics:
    enabled: true
    service:
      type: NodePort
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    serviceMonitor:
      enabled: true
      additionalLabels: {}
      interval: 30s
      scrapeTimeout: 10s
    config:
      datasourceSecret:
        name: otusdemo-secret
        key: DB_URI

metrics:
  serviceMonitor:
    enabled: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths: [/otusapp($|/)(.*)]