# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: arahna/otusdemo
  pullPolicy: IfNotPresent
  tag: release-0.2.1

service:
  type: NodePort
  port: 9000

postgresql:
  enabled: true
  postgresqlURI: postgresql+psycopg2://otus:otuspwd@postgres:5432/otusdemo

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths: [/otusapp($|/)(.*)]